### PR TITLE
Abolish run-test script and define a rake task to run all tests and also to allow developers to choose one test to run

### PR DESCRIPTION
**Pull request by satoryu**
Let's ride on best practice of test-unit.

### CODE REVIEW

**Comment by satoryu** [comment]
Executing test `test/test_storage.rb` fails. the crash report is:

```
Process:               ruby [70679]
Path:                  /usr/local/var/rbenv/versions/2.1.5/bin/ruby
Identifier:            ruby
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ruby [70666]
Responsible:           iTerm2 [460]
User ID:               1423175629

Date/Time:             2016-07-31 21:23:53.886 +0900
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11
Anonymous UUID:        EC7F55D2-C7AA-2336-644E-63808ED153AA

Sleep/Wake UUID:       CDEDEFB2-AA78-4635-B991-B0003AD6967C

Time Awake Since Boot: 21000 seconds
Time Since Wake:       160 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000041a0

VM Regions Near 0x41a0:
--> 
    __TEXT                 0000000102f99000-00000001031ab000 [ 2120K] r-x/rwx SM=COW  /usr/local/var/rbenv/versions/2.1.5/bin/ruby

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff918caf06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff993a54ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9056b6df abort + 129
3   ruby                          	0x0000000102fd9d19 rb_bug + 185
4   ruby                          	0x00000001030a8ebc sigsegv + 156
5   libsystem_platform.dylib      	0x00007fff973ea52a _sigtramp + 26
6   ???                           	000000000000000000 0 + 0
7   groonga.bundle                	0x00000001039a4f1b rb_grn_database_mark + 75
8   ruby                          	0x0000000102ffa63a gc_mark_children + 2442
9   ruby                          	0x00000001030015bf gc_marks_body + 479
10  ruby                          	0x0000000102fff42b garbage_collect_body + 859
11  ruby                          	0x0000000102ff5e1b newobj_of + 571
12  ruby                          	0x00000001030b6c93 str_new0 + 83
13  ruby                          	0x00000001030b6c0d rb_enc_str_new + 45
14  groonga.bundle                	0x00000001039bc34d rb_grn_key_to_ruby_object + 77
15  groonga.bundle                	0x00000001039b3742 rb_grn_table_key_support_get_key + 370
16  ruby                          	0x000000010312726e vm_call_cfunc + 1054
17  ruby                          	0x000000010310d0f6 vm_exec_core + 12742
18  ruby                          	0x000000010311c301 vm_exec + 129
19  ruby                          	0x0000000103121074 invoke_block_from_c + 2404
20  ruby                          	0x0000000103118b08 rb_yield + 184
21  groonga.bundle                	0x00000001039b86f6 rb_grn_table_each_body + 86
22  ruby                          	0x0000000102fe359e rb_ensure + 174
23  groonga.bundle                	0x00000001039b677e rb_grn_table_each + 94
24  ruby                          	0x000000010312726e vm_call_cfunc + 1054
25  ruby                          	0x000000010310d0f6 vm_exec_core + 12742
26  ruby                          	0x000000010311c301 vm_exec + 129
27  ruby                          	0x0000000103121074 invoke_block_from_c + 2404
28  ruby                          	0x0000000103118b08 rb_yield + 184
29  ruby                          	0x0000000103032258 int_dotimes + 56
30  ruby                          	0x000000010312726e vm_call_cfunc + 1054
31  ruby                          	0x000000010310d0f6 vm_exec_core + 12742
32  ruby                          	0x000000010311c301 vm_exec + 129
33  ruby                          	0x0000000103121074 invoke_block_from_c + 2404
34  ruby                          	0x000000010311b53a vm_invoke_proc + 186
35  ruby                          	0x000000010311b470 rb_vm_invoke_proc + 32
36  ruby                          	0x0000000102fe7ee1 rb_proc_call + 81
37  ruby                          	0x0000000102fe1cf7 rb_exec_end_proc + 327
38  ruby                          	0x0000000102fe21fe ruby_finalize_0 + 110
39  ruby                          	0x0000000102fe234e ruby_cleanup + 318
40  ruby                          	0x0000000102fe2605 ruby_run_node + 85
41  ruby                          	0x0000000102f99daf main + 79
42  libdyld.dylib                 	0x00007fff88fd95ad start + 1

Thread 1:: ruby-timer-thr
0   libsystem_kernel.dylib        	0x00007fff918cc2a2 poll + 10
1   ruby                          	0x00000001031371e3 thread_timer + 371
2   libsystem_pthread.dylib       	0x00007fff993a299d _pthread_body + 131
3   libsystem_pthread.dylib       	0x00007fff993a291a _pthread_start + 168
4   libsystem_pthread.dylib       	0x00007fff993a0351 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fc5e10f3318  rdx: 0x0000000000000000
  rdi: 0x0000000000000a0b  rsi: 0x0000000000000006  rbp: 0x00007fc5e10f3340  rsp: 0x00007fc5e10f3318
   r8: 0x0000000000000040   r9: 0x00007fff78b051e0  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fc5e442d7f0  r13: 0x0000000000000000  r14: 0x00007fff79f6c000  r15: 0x0000000000000000
  rip: 0x00007fff918caf06  rfl: 0x0000000000000206  cr2: 0x00007fff78b03008
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x102f99000 -        0x1031aaff7 +ruby (0) <A48621B8-5248-3B83-9371-FA210A09565C> /usr/local/var/rbenv/versions/2.1.5/bin/ruby
       0x103547000 -        0x103548ff7 +encdb.bundle (0) <A3E05A10-3206-37DA-8C57-E61E06781040> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/encdb.bundle
       0x10354b000 -        0x10354cfff +transdb.bundle (0) <8310D705-D614-35B7-AB1E-92CFBC1480F5> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/trans/transdb.bundle
       0x103571000 -        0x103573ff7 +thread.bundle (0) <E77B7091-53FE-3995-9D7B-42C30BFEB176> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/thread.bundle
       0x103576000 -        0x10357bff7 +pathname.bundle (0) <17EBF4CB-6662-3F21-AA3F-EF51E3DE72E4> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/pathname.bundle
       0x103580000 -        0x103581ff7 +console.bundle (0) <81BFBEA9-6DFE-37D4-B848-6FF899475EE0> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/io/console.bundle
       0x103584000 -        0x103585fff +etc.bundle (0) <629C5F71-BA76-31DE-A241-62AC61E63DEB> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/etc.bundle
       0x103588000 -        0x10358bfff +strscan.bundle (0) <7B117D94-CBB8-3A8F-9A80-BB0BF4681723> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/strscan.bundle
       0x10358f000 -        0x10358ffff +sha1.bundle (0) <A5BC7CFF-6CDB-35DA-AA02-D7888823CBA2> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/digest/sha1.bundle
       0x103592000 -        0x103703a6f +libcrypto.1.0.0.dylib (0) <9DDCB4D1-F1F7-3996-A174-282BC1E18ECA> /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
       0x10377b000 -        0x1037b9ff7 +libssl.1.0.0.dylib (0) <0624F8A6-D663-3336-8E9E-394645F40C92> /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
       0x1037d6000 -        0x1037d7fff +digest.bundle (0) <1CAF0DF8-DF30-3A80-8E28-5C5C20EB4C62> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/digest.bundle
       0x1037db000 -        0x1037f9fff +socket.bundle (0) <E57D6B69-B78E-3EF4-BCA0-E48463B6F35A> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/socket.bundle
       0x103802000 -        0x10380cfff +zlib.bundle (0) <23909218-9732-311E-B46D-4EBA3AFC386F> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/zlib.bundle
       0x103812000 -        0x103816ff7 +stringio.bundle (0) <AC86A7B1-D4C2-308D-8729-D7660A171831> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/stringio.bundle
       0x10381a000 -        0x103860ff7 +date_core.bundle (0) <66044454-475A-3E8A-9569-F914C8938531> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/date_core.bundle
       0x103871000 -        0x103871ff7 +fcntl.bundle (0) <22BD23D0-DF80-3C85-85E0-F842F9083DC3> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/fcntl.bundle
       0x103874000 -        0x1038a5fff +openssl.bundle (0) <0EA02A59-6308-3DEF-9659-5EAA0FCC2F42> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/openssl.bundle
       0x1038c2000 -        0x1038f6fff +ripper.bundle (0) <C0F4A4C1-E35F-3DA5-B4FB-0B737B8D64C5> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/ripper.bundle
       0x1038fe000 -        0x10391dfff +psych.bundle (0) <B6067DD8-DD97-38AA-95FF-B67ED3D09869> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/psych.bundle
       0x103923000 -        0x103930ff3 +tokyocabinet.bundle (0) <172C02CE-7664-3CAF-BBE1-B25146C8E37E> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/extensions/x86_64-darwin-14/2.1.0-static/tokyocabinet-ruby-a3bb9d8fd80f/tokyocabinet.bundle
       0x103938000 -        0x103992ff7 +libtokyocabinet.9.dylib (0) <D568D8BD-B84F-3255-AE20-874F39FA3CEB> /usr/local/opt/tokyo-cabinet/lib/libtokyocabinet.9.dylib
       0x1039a0000 -        0x1039c1ff7 +groonga.bundle (0) <AEDA6C09-5176-3D35-BD62-15AF1D868E06> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/rroonga-4.0.8/groonga.bundle
       0x1039d2000 -        0x103c17ff7 +libgroonga.0.dylib (0) <608FD3CC-3A23-30FF-AAF5-3162FF59D112> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rroonga-4.0.8/vendor/local/lib/libgroonga.0.dylib
       0x104186000 -        0x104189ffb +parser.bundle (0) <908EE508-A136-3D6D-B9AF-1E9846F57D33> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/json-1.8.2/json/ext/parser.bundle
       0x10418d000 -        0x10418dfff +utf_16be.bundle (0) <616ADBA8-4954-3E28-952B-9518B5C9658F> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/utf_16be.bundle
       0x104190000 -        0x104190fff +utf_16le.bundle (0) <4B056025-BE43-31F1-86D3-D2E3015A4E1E> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/utf_16le.bundle
       0x104193000 -        0x104193ff7 +utf_32be.bundle (0) <BE4C115C-A372-3197-A408-2AF67CF5EDA3> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/utf_32be.bundle
       0x104196000 -        0x104196ff7 +utf_32le.bundle (0) <13B67885-04F5-353E-A40B-6D33E272813A> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/x86_64-darwin14.0/enc/utf_32le.bundle
       0x104199000 -        0x10419fff7 +generator.bundle (0) <2871F941-4582-3E35-BF5C-5B308D35F6D7> /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/json-1.8.2/json/ext/generator.bundle
    0x7fff67a66000 -     0x7fff67a9da47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff861b6000 -     0x7fff863c3fff  libicucore.A.dylib (551.51.4) <3899B146-3840-3D4A-8C4A-FE391D5D25C7> /usr/lib/libicucore.A.dylib
    0x7fff88fd6000 -     0x7fff88fd9ffb  libdyld.dylib (360.22) <1F9FCF2C-5E94-3F2D-B4A5-1238587AA5C6> /usr/lib/system/libdyld.dylib
    0x7fff8916d000 -     0x7fff89175fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff8925e000 -     0x7fff896d4fff  com.apple.CoreFoundation (6.9 - 1258.1) <943A1383-DA6A-3DC0-ABCD-D9AEB3D0D34D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff89c64000 -     0x7fff89c6cffb  libsystem_dnssd.dylib (625.60.4) <80189998-32B0-316C-B5C5-53857486713D> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8a118000 -     0x7fff8a12fff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff8a150000 -     0x7fff8a17fffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff8a180000 -     0x7fff8a189ff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff8a9b1000 -     0x7fff8a9b2ffb  libSystem.B.dylib (1226.10.1) <ECAA07BE-A114-3461-AA13-C57838775FC2> /usr/lib/libSystem.B.dylib
    0x7fff8abb3000 -     0x7fff8abbbfff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff8abbc000 -     0x7fff8abe6ff7  libc++abi.dylib (307.2) <922EFB36-0E9E-315B-8270-E81AC43472C0> /usr/lib/libc++abi.dylib
    0x7fff8b16f000 -     0x7fff8b171ff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff8b3f1000 -     0x7fff8b3f5fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff8d41b000 -     0x7fff8d41efff  libsystem_sandbox.dylib (460.60.2) <2A68B39C-B786-3A05-87A2-56E688469FB8> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8f8b8000 -     0x7fff8f8e1fff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fff902b3000 -     0x7fff902b3ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff9050d000 -     0x7fff9059afef  libsystem_c.dylib (1082.60.1) <28733D22-553E-3CBC-8D2C-EDCEB46E46AF> /usr/lib/system/libsystem_c.dylib
    0x7fff905ea000 -     0x7fff90601ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff90602000 -     0x7fff90604ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff909cb000 -     0x7fff909d2ff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff90a34000 -     0x7fff90a61fff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff91897000 -     0x7fff918b3ff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff918b4000 -     0x7fff918d2ff7  libsystem_kernel.dylib (3248.60.10) <C1A6A0B9-1869-36AB-B4A2-D862EB09A4BE> /usr/lib/system/libsystem_kernel.dylib
    0x7fff918d3000 -     0x7fff918e1ff7  libbz2.1.0.dylib (38) <28E54258-C0FE-38D4-AB76-1734CACCB344> /usr/lib/libbz2.1.0.dylib
    0x7fff921a7000 -     0x7fff921b2ff7  libcommonCrypto.dylib (60075.50.1) <93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib
    0x7fff925b6000 -     0x7fff925b7ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff92c5c000 -     0x7fff92cc2ff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib
    0x7fff94bee000 -     0x7fff94beffff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff9557f000 -     0x7fff95584ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff96844000 -     0x7fff96844ff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff96954000 -     0x7fff96cbf657  libobjc.A.dylib (680) <D55D5807-1FBE-32A5-9105-44D7AFE68C27> /usr/lib/libobjc.A.dylib
    0x7fff97343000 -     0x7fff97354ff7  libsystem_trace.dylib (201.10.3) <1DD0C1FD-74E2-3949-9C2C-B81D19C2CA5E> /usr/lib/system/libsystem_trace.dylib
    0x7fff973e8000 -     0x7fff973f0fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff9824c000 -     0x7fff9824dfff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff982df000 -     0x7fff98356feb  libcorecrypto.dylib (335.50.1) <B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib
    0x7fff985c1000 -     0x7fff985eaff7  libxpc.dylib (765.50.8) <54D1328E-054E-3DAA-89E2-375722F9D18F> /usr/lib/system/libxpc.dylib
    0x7fff985ec000 -     0x7fff985eefff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff985ef000 -     0x7fff985efff7  liblaunch.dylib (765.50.8) <834ED605-5114-3641-AA4D-ECF31B801C50> /usr/lib/system/liblaunch.dylib
    0x7fff9939f000 -     0x7fff993a8ff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff993fa000 -     0x7fff99440ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff9a2f3000 -     0x7fff9a2f4fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff9a7e3000 -     0x7fff9a7f4ff7  libz.1.dylib (61.20.1) <B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib
    0x7fff9a7f5000 -     0x7fff9a7faff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff9c9b7000 -     0x7fff9ca0aff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 10883
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=114.6M resident=0K(0%) swapped_out_or_unallocated=114.6M(100%)
Writable regions: Total=213.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=213.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                           153.2M       32 
MALLOC guard page                   16K        4 
STACK GUARD                          4K        2 
Stack                             8216K        3 
Stack Guard                       56.0M        2 
VM_ALLOCATE                       49.8M       75 
__DATA                            3436K       81 
__LINKEDIT                        92.8M       33 
__TEXT                            21.9M       76 
__UNICODE                          552K        2 
mapped file                      263.9M       84 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            651.4M      388 
```

**Comment by kou** [comment]
It's caused by replacing `test/run-test.rb` with `Rake::TestTask`.
`Rake::TestTask` uses `at_exit` trick to run tests automatically. `test/run-test.rb` doesn't use `at_exit` trick to run tests. It uses `Test::Unit::AutoRunner` explicitly.

Rroonga also uses `at_exit` to finalize `libgroonga`. If `require "groonga"` is evaluated after `require "test/unit"`, `at_exit` proc for Rroonga is defined after `at_exit` proc for test-unit. It means that `libgroonga` is finalized then tests are started. It causes crash.

Here is a workaround:

```diff
diff --git a/test/test_helper.rb b/test/test_helper.rb
index e3469b8..fb36ef5 100755
--- a/test/test_helper.rb
+++ b/test/test_helper.rb
@@ -1,2 +1,3 @@
+require 'groonga'
 require 'test/unit'
 require 'roma_test_utils'
```

I'll change Rroonga to use `ObjectSpace#define_finalizer` against `Groonga` module instead of `at_exit`. Finalizers for constants are always ran after `at_exit` procs.

**Comment by kou** [comment]
> I'll change Rroonga to use `ObjectSpace#define_finalizer` against `Groonga` module instead of `at_exit`.

I've released Rroonga 6.0.7 that includes the change.

**Comment by satoryu** [comment]
@kou san, thank you for your work 🎉  I confirmed that the problem doesn't happen with the latest version of rroonga.

**Pull request merged**
