### PR TITLE
Fix test failure on travis

### PR DESCRIPTION
**Pull request by satoryu**
The current HEAD of the master branch could not pass one test and as for ruby 2.3.1 failed to install gems on which roma depends.

### CODE REVIEW

**Comment by satoryu** [comment]
All tests got able to run but not passed yet. https://travis-ci.org/roma/roma/jobs/133544014#L240-L266

**Comment by snowmantw** [comment]
Hi @satoryu I've found the one CI failure, which is not only in 2.3.1 but also [in 2.1](https://travis-ci.org/roma/roma/jobs/135247494#L248 ) and is about:

    localhost_11211 #<NoMethodError: undefined method `write' for nil:NilClass>

looks because of `TCPSocket.new` in `lib/roma/messaging/con_pool.rb` sometime fail to create new socket. And the message shows it has been refused by system, suggesting port may has been occupied. I now try to figure out who occupies the port and didn't release it, including the suspicious case from aborted or failed tests who may not clean itself well. I don't know if you're already working on this issue since this PR/issue is for 2.3.1, but if not I'll keep working on that.

**Comment by satoryu** [comment]
As I tried to test for all 2.1 series, the error was reproduced with only ruby 2.1.0. https://travis-ci.org/roma/roma/jobs/135381815#L280-L290

**Comment by satoryu** [comment]
- [ ] Merge #137 @snowmantw 's great work with this branch. 
- [ ] Merge this PR if it passes all tests.

**Pull request merged**
