### PR TITLE
Use travis

### PR DESCRIPTION
**Pull request by satoryu**
Now there are no shared environment for CI for ROMA. So every developer has to prepare testing environment by themselves. It has made some developers struggled to doing it and discouraged some developers from contributing ROMA. 

This pull-request provides a configuration to use Travis CI, well-known CI platform and no charge for OSS project.

### CODE REVIEW

**Comment by satoryu** [comment]
:feelsgood:  https://travis-ci.org/satoryu/roma/builds/96562852

**Comment by byplayer** [comment]
build fail..., but pull request looks nice.

**Comment by satoryu** [comment]
Do you know whether these failure are known bugs or not? 
If not, it means that I have to modify `.travis.yml` so that a build VM can prepare an environment for testing ROMA. 

CC: @hiroaki-iwase

**Comment by hiroaki-iwase** [comment]
1 failure(Failure: test_get_expt(ProtocolTest)) resulted from timezone problem.
So I fixed it just now.
https://github.com/roma/roma/commit/b5ba2258810f2c85c47e56db552cdf352bd5d098

And part of another error(Failure: test_rc_other_store_cmd(ClusterReplicationTest)),  which I could pass via '-n' option.

    # ruby test/run-test.rb -n test_rc_other_store_cmd
    Finished in 8.297304467 seconds.
    ------------------------------------------------------------------------------------------------------
    1 tests, 17 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
    100% passed
    --------------------------------------------------------------------------------------------------------

So I will check it again.

**Comment by PatelParas** [comment]
Better to move travis ownership from personal account to "ROMA" organisation account to prevent future permission issue so anybody can do required changes if possible.

**Comment by hiroaki-iwase** [comment]
I modified some logic for below error and sent pull req.
- test_rc_other_store_cmd
- test_get_expt

Please confirm it.

And Current ROMA does't support ruby v2.2.x.
Probably it works well, but 1 test case took much time due to changing of Ruby logic or difference of minitest and test-unit gem.
(https://github.com/roma/roma/blob/master/test/t_routing_data.rb#L83)
So please use ruby 2.1.x

**Comment by satoryu** [comment]
FYI: `libtokyocabinet-dev` is available on Container-based CI of Travis. travis-ci/apt-package-whitelist#2069 :tada:

**Comment by hiroaki-iwase** [comment]
congratulations!
Thanks!!

**Comment by satoryu** [comment]
:feelsgood: https://travis-ci.org/roma/roma/jobs/105834954#L204 failed ... 

wat is `#<TypeError: no implicit conversion of nil into String>` ?

**Comment by satoryu** [comment]
Although this PR still fails, I think this can be merged since 

* this PR doesn't have any update on roma itself.
* @hiroaki-iwase has a great branch for fixing this failure (satoryu/roma#4) 

I will merge the PR into the master if get 4 or more :+1:  :)

**Comment by PatelParas** [comment]
Still Fails :(

**Comment by satoryu** [comment]
I know the code base cannot pass all the test on CI environment. but as I already mentioned, this PR does not have any update on the code base. 

I'll try to fix the failure of tests later.

**Pull request merged**
