### PR TITLE
Removed unnecessary comments from log_shift test script

### PR DESCRIPTION
**Pull request by PatelParas**

### CODE REVIEW

**Comment by satoryu** [comment]
It looks to me that this PR only updates the comments in test cases to make it more meaningful and no updates are made.  

I think this can be merged into the master branch. 
How about this? @tarr1124 @PatelParas  
I will merge if you are ok.

**Comment by PatelParas** [comment]
No problem

**Comment by satoryu** [comment]
@PatelParas I din't know the target branch of this PR is not master. so I will pick up your commit  and put it to the master branch later.

**Comment by satoryu** [comment]
Did it! e45bdfc646a56ea7a4b0a506235206d0eb6417f6

**Pull request merged**
